# Generated by Django 3.1 on 2020-08-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='modified_at',
            new_name='date_modified',
        ),
    ]
